#!/usr/bin/env bun
/**
 * Emit `src/guard/vx-names.ts` — every `--vx-*` name basalt emits, the allowlist behind the
 * `unknown-vx-token` guard kind.
 *
 * The guard is dependency-free by contract, so it cannot import `src/tokens` at runtime; it reads a
 * checked-in literal instead. That literal is derived, never hand-edited, from two sources:
 *
 * 1. `buildPaletteCss()` with no options — the exact function `gen-tokens-css.mjs` writes
 *    `dist/tokens.css` from, so the palette half IS the published stylesheet's name set.
 * 2. The component-scoped names basalt's own source declares (`--vx-hit-gap`,
 *    `--vx-space-icon-size`, `--vx-keyboard-inset`): a CSS declaration or a quoted string literal
 *    in a non-test file outside `src/guard/`.
 *
 * `src/guard/vx-names.test.ts` re-derives the set and fails on any drift, pointing back here.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { Glob } from 'bun'
import { buildPaletteCss } from '../src/tokens/index.ts'

const ROOT = resolve(import.meta.dirname, '..')
export const VX_NAMES_PATH = resolve(ROOT, 'src/guard/vx-names.ts')

const DECLARATION = /(--vx-[A-Za-z0-9-]*[A-Za-z0-9])\s*:/g
const QUOTED = /['"](--vx-[A-Za-z0-9-]*[A-Za-z0-9])['"]/g

export function collectVxNames(): string[] {
  const names = new Set<string>()
  for (const m of buildPaletteCss().matchAll(DECLARATION)) names.add(m[1] ?? '')
  for (const rel of new Glob('src/**/*.{ts,tsx,css}').scanSync(ROOT)) {
    if (rel.startsWith('src/guard/') || /\.test\.tsx?$/.test(rel)) continue
    const text = readFileSync(resolve(ROOT, rel), 'utf8')
    const re = rel.endsWith('.css') ? DECLARATION : QUOTED
    for (const m of text.matchAll(re)) names.add(m[1] ?? '')
  }
  return [...names].toSorted()
}

export function renderVxNames(names: readonly string[]): string {
  return [
    '// GENERATED by scripts/gen-vx-names.ts — do not edit. `vx-names.test.ts` fails on drift.',
    '',
    '/** Every `--vx-*` name basalt emits: `dist/tokens.css` plus its component-scoped names. */',
    'export const BASALT_VX_NAMES: readonly string[] = [',
    ...names.map((n) => `  '${n}',`),
    ']',
    '',
  ].join('\n')
}

if (import.meta.main) {
  const names = collectVxNames()
  writeFileSync(VX_NAMES_PATH, renderVxNames(names))
  console.log(`gen-vx-names: ${names.length} names → src/guard/vx-names.ts`)
}
