#!/usr/bin/env bun
/**
 * Emit `src/guard/vx-names.ts` — every `--vx-*` name basalt emits, the allowlist behind the
 * `unknown-vx-token` guard kind.
 *
 * The guard is dependency-free by contract, so it cannot import `src/tokens` at runtime; it reads a
 * checked-in literal instead. That literal is derived, never hand-edited, from two sources:
 *
 * 1. `buildPaletteCss()` with no options — the exact function `gen-tokens-css.mjs` writes
 *    `dist/tokens.css` from, so the palette half IS the published stylesheet's name set.
 * 2. The component-scoped names basalt's own source declares (`--vx-hit-gap`,
 *    `--vx-space-icon-size`, `--vx-keyboard-inset`), from every non-test file outside `src/guard/`:
 *    a declaration (`--vx-x:` — in a `.css` file or in CSS text inside a `.ts`/`.tsx` template
 *    literal) and, in `.ts`/`.tsx`, ANY quoted `'--vx-x'` string literal. The quoted form is
 *    deliberately broad — a style-object key, a `setProperty` name, a const — so a quoted
 *    `--vx-*` anywhere in shipped source enters the allowlist. That errs toward NOT reporting; it
 *    can never make the guard flag a name basalt emits.
 *
 * `src/guard/vx-names.test.ts` re-derives the set and fails on any drift, pointing back here.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { Glob } from 'bun'
import { buildPaletteCss } from '../src/tokens/index.ts'

const ROOT = resolve(import.meta.dirname, '..')
export const VX_NAMES_PATH = resolve(ROOT, 'src/guard/vx-names.ts')

const DECLARATION = /(--vx-[A-Za-z0-9-]*[A-Za-z0-9])\s*:/g
const QUOTED = /['"](--vx-[A-Za-z0-9-]*[A-Za-z0-9])['"]/g

export function collectVxNames(): string[] {
  const names = new Set<string>()
  const add = (text: string, re: RegExp) => {
    for (const [, name] of text.matchAll(re)) names.add(name as string) // group 1 is not optional
  }
  add(buildPaletteCss(), DECLARATION)
  for (const rel of new Glob('src/**/*.{ts,tsx,css}').scanSync(ROOT)) {
    if (rel.startsWith('src/guard/') || /\.test\.tsx?$/.test(rel)) continue
    const text = readFileSync(resolve(ROOT, rel), 'utf8')
    add(text, DECLARATION)
    if (!rel.endsWith('.css')) add(text, QUOTED)
  }
  return [...names].toSorted()
}

export function renderVxNames(names: readonly string[]): string {
  return [
    '// GENERATED by scripts/gen-vx-names.ts — do not edit. `vx-names.test.ts` fails on drift.',
    '',
    '/** Every `--vx-*` name basalt emits: `dist/tokens.css` plus its component-scoped names. */',
    'export const BASALT_VX_NAMES: readonly string[] = [',
    ...names.map((n) => `  '${n}',`),
    ']',
    '',
  ].join('\n')
}

if (import.meta.main) {
  const names = collectVxNames()
  writeFileSync(VX_NAMES_PATH, renderVxNames(names))
  console.log(`gen-vx-names: ${names.length} names → src/guard/vx-names.ts`)
}
