/**
 * Performs MIGRATING.md's release-time rename: `## Unreleased — <title>` becomes
 * `## <version> — <title>`, the § "What changed, by surface" index takes the same number in its
 * last column head, and a fresh empty `## Unreleased` section plus a fresh `Unreleased` column open
 * above them.
 *
 * WHY THIS IS A SCRIPT. The rename was an authoring-time step done by hand, and it failed four
 * releases running — 1.27.0, 1.28.0 and 1.29.0 all shipped under one `## Unreleased` heading, and
 * 1.30.0 shipped one to npm on its own. MIGRATING's preamble has claimed since 1.30.0 that the swap
 * "belongs" in `.releaserc.json`'s `prepareCmd`; it was never actually put there, and MIGRATING.md
 * was not in `@semantic-release/git`'s assets either, so even a correct local edit could not have
 * reached the tarball. `llms.txt` is the shape that works — regenerated by `prepareCmd`, committed
 * through the same assets list — and this is its equivalent for MIGRATING.
 *
 * IT FAILS CLOSED. Every unexpected shape throws instead of leaving the file alone, because
 * "silently did nothing" is the exact failure this replaces. `--check` runs the whole transform
 * against the committed file and discards the result, so `scripts/release.sh` can prove the rename
 * WILL work before it dispatches anything — semantic-release skips `prepare` in a dry run, so the
 * dry run cannot exercise this and the preflight is the only place it can be caught early.
 *
 * Usage: bun packages/basalt-ui/scripts/release-migrating.ts 1.31.0
 *        bun packages/basalt-ui/scripts/release-migrating.ts --check  (shape gate, writes nothing)
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = join(import.meta.dirname, '..', '..', '..')

export const migratingPath = join(root, 'packages/basalt-ui/MIGRATING.md')

/** The heading the newest section is authored under, and the index column head that pairs with it. */
const UNRELEASED = 'Unreleased'

/** The index this rewrites — anchored by its own h2 so the file's ~20 other tables are untouched. */
const INDEX_HEADING = '## What changed, by surface'

/**
 * Advisory only. The index has held three released columns plus `Unreleased` for several
 * revisions; every cell is a POINTER to a section that stays in the file, so trimming the oldest
 * column loses a routing hint and no content. Past this width the row wraps unreadably — but a
 * release must not fail over a table's width, and dropping a column automatically would be an
 * editorial decision this script has no business making. So: warn, and let the author trim.
 */
const INDEX_COLUMN_SOFT_MAX = 6

const VERSION_RE = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/

/** Splits `| a | b |` into its cells, dropping the empty edges the leading/trailing pipes produce. */
function cellsOf(row: string): string[] {
  return row
    .split('|')
    .slice(1, -1)
    .map((cell) => cell.trim())
}

function rowOf(cells: readonly string[]): string {
  return `| ${cells.join(' | ')} |`
}

/**
 * The whole rename, as a pure string transform so the test can assert on it without touching the
 * real file. Throws — never returns the input unchanged — when the file is not in a shape it
 * recognises.
 */
export function renameUnreleased(markdown: string, version: string): string {
  if (!VERSION_RE.test(version)) {
    throw new Error(
      `release-migrating: '${version}' is not a version — refusing to write it as a heading`,
    )
  }

  const lines = markdown.split('\n')

  // ── The section heading ──────────────────────────────────────────────────────
  const headingIdxs = lines
    .map((line, i) => (new RegExp(`^## ${UNRELEASED}(?:$|\\s)`).test(line) ? i : -1))
    .filter((i) => i !== -1)

  if (headingIdxs.length !== 1) {
    throw new Error(
      `release-migrating: expected exactly one '## ${UNRELEASED}' section heading, found ` +
        `${headingIdxs.length}. The newest section must be authored as '## ${UNRELEASED} — <title>'.`,
    )
  }

  const headingIdx = headingIdxs[0] as number
  const heading = lines[headingIdx] as string
  // The title (everything after `Unreleased`) is carried over verbatim; only the word moves.
  lines[headingIdx] = heading.replace(`## ${UNRELEASED}`, `## ${version}`)

  // The fresh section opens ABOVE the one just named, so the file stays newest-first.
  lines.splice(
    headingIdx,
    0,
    `## ${UNRELEASED}`,
    '',
    '_Nothing yet. Author the next section under this heading as `## Unreleased — <title>`; the',
    'release renames it and opens a new one here._',
    '',
  )

  // ── The surface index ────────────────────────────────────────────────────────
  const indexIdx = lines.findIndex((line) => line.startsWith(INDEX_HEADING))
  if (indexIdx === -1) {
    throw new Error(`release-migrating: '${INDEX_HEADING}' section not found`)
  }

  const headerIdx = lines.findIndex((line, i) => i > indexIdx && line.trimStart().startsWith('|'))
  if (headerIdx === -1 || !(lines[headerIdx + 1] ?? '').trimStart().startsWith('|')) {
    throw new Error(`release-migrating: no table found under '${INDEX_HEADING}'`)
  }

  const header = cellsOf(lines[headerIdx] as string)
  if (header[header.length - 1] !== UNRELEASED) {
    throw new Error(
      `release-migrating: the index's last column is headed '${header[header.length - 1]}', not ` +
        `'${UNRELEASED}' — it was already renamed, or the table changed shape.`,
    )
  }

  header[header.length - 1] = version
  header.push(UNRELEASED)
  lines[headerIdx] = rowOf(header)

  const separator = cellsOf(lines[headerIdx + 1] as string)
  separator.push('---')
  lines[headerIdx + 1] = rowOf(separator)

  // Every surface starts the new cycle with no delta; the author fills a cell in when there is one.
  for (let i = headerIdx + 2; i < lines.length; i++) {
    const line = lines[i] as string
    if (!line.trimStart().startsWith('|')) break
    lines[i] = rowOf([...cellsOf(line), '—'])
  }

  if (header.length - 1 > INDEX_COLUMN_SOFT_MAX) {
    console.warn(
      `⚠ release-migrating: the surface index now carries ${header.length - 1} version columns ` +
        `(soft max ${INDEX_COLUMN_SOFT_MAX}). Trim the oldest — its cells only point at sections ` +
        `that stay in the file.`,
    )
  }

  return lines.join('\n')
}

/**
 * Re-aligns the rewritten tables. `fmt:check` covers `packages/**\/*.md`, and the release commit
 * carries `[skip ci]` — so an unformatted MIGRATING would not go red on the release, it would go
 * red on the next PR, for a reason nobody would connect to a release two weeks earlier. Same
 * argument `.oxfmtignore` makes for CHANGELOG.md, reached from the other side: this file IS
 * formatter-owned, so the generator has to leave it formatted.
 */
function formatInPlace(path: string): void {
  const bin = join(root, 'node_modules/.bin/oxfmt')
  const result = Bun.spawnSync([bin, path], { stdout: 'pipe', stderr: 'pipe' })
  if (!result.success) {
    throw new Error(`release-migrating: oxfmt failed on ${path}\n${result.stderr.toString()}`)
  }
}

function main(): void {
  const args = process.argv.slice(2)
  const markdown = readFileSync(migratingPath, 'utf8')

  if (args.includes('--check')) {
    // Runs the real transform and throws the real errors — a check that only pattern-matched would
    // be a second implementation to keep in sync with the first.
    renameUnreleased(markdown, '0.0.0')
    console.log('✓ release-migrating --check: MIGRATING.md is in a shape the release can rename.')
    return
  }

  const version = args[0]
  if (version === undefined) {
    console.error('usage: bun packages/basalt-ui/scripts/release-migrating.ts <version> | --check')
    process.exit(2)
  }

  writeFileSync(migratingPath, renameUnreleased(markdown, version), 'utf8')
  formatInPlace(migratingPath)
  console.log(`wrote ${migratingPath} — '## ${UNRELEASED}' is now '## ${version}'`)
}

if (import.meta.path === Bun.main) {
  main()
}
