/**
 * The mobile `Filters (n)` sheet (`docs/CONTROLS-SPEC.md` §2.1/§3) — a bottom `Drawer` around the
 * SAME `PanelRow` forms the aside's `panel` surface renders (`useFilterSurface` resolves `'sheet'`
 * and `'panel'` to the identical control body; only the surrounding chrome differs). Every child of
 * the `FilterSet` renders its full-width form inside it, edits APPLY IMMEDIATELY (there is no Apply
 * button — the URL is the truth and a filter write is already `history: 'replace'`), and one
 * `Reset all` (in the header, not a footer — see this module's doc below) clears every registered
 * filter.
 *
 * This module used to also own the sheet's OWN row primitives — a `SheetOptionList` of 44px rows
 * with a hairline between them, one per option. That did not scale (`docs/CONTROLS-SPEC.md` §3): a
 * filter with many options became a sheet as tall as the set, where the panel's own `PanelChoice`
 * (a track, or a `Select` past three) and `MultiSelectFilter`'s facet fold both already had an
 * answer. Deleted with it: `SheetField`, `SheetOptionList`, `SheetDisclosure`, `SheetRow` and
 * `sheetRowClassNames` (`MIGRATING.md`).
 *
 * INTERNAL, like `FilterPill`: `FilterSet` owns when the sheet opens, so a consumer mounting it by
 * hand would own a second, unregistered filter home (C1).
 */
import { Button, Drawer } from '@mantine/core'
import { useId } from 'react'
import type { ReactNode } from 'react'
import type { BasaltProps } from '../common/props'
import classes from './controls.module.css'

export type FilterSheetProps = BasaltProps & {
  readonly opened: boolean
  readonly onClose: () => void
  /**
   * Clears every registered filter. OMITTED on a sheet with no census behind it — the aside's
   * mobile projection (`docs/ASIDE-SPEC.md` §0) mounts its children under a `null` registry, so
   * there is nothing to reset and a button that resets nothing is worse than no button.
   */
  readonly onResetAll?: () => void
  readonly title?: string
  readonly children: ReactNode
}

/**
 * `Reset all` rides the HEADER, beside the title and the close ×, not a footer.
 *
 * A bottom drawer's footer is the one region a phone cannot promise is on screen: the sheet grows
 * with its content, so with six filters open the reset button sat below the fold and the only way to
 * reach it was to scroll past every row it would have undone. The header is fixed by construction.
 * It also removes the sheet's last horizontal rule — a footer needs separating from the rows above
 * it, a header does not (`docs/CONTROLS-SPEC.md` §2.1: hairlines between OPTION rows only).
 */
export function FilterSheet({
  opened,
  onClose,
  onResetAll,
  title = 'Filters',
  children,
  className,
  style,
}: FilterSheetProps): ReactNode {
  return (
    <Drawer
      opened={opened}
      onClose={onClose}
      position="bottom"
      radius="sm"
      classNames={{ header: classes.sheetHeader, title: classes.sheetTitle }}
      {...(className !== undefined && { className })}
      {...(style !== undefined && { style })}
      title={
        <>
          <span className={classes.sheetTitleText}>{title}</span>
          {onResetAll !== undefined && (
            <Button variant="subtle" size="ctl" onClick={onResetAll}>
              Reset all
            </Button>
          )}
        </>
      }
    >
      <div className={classes.sheetBody}>{children}</div>
    </Drawer>
  )
}

/**
 * The selected-row mark — 16px, drawn at the row's trailing edge (`docs/CONTROLS-SPEC.md` §2.1).
 * Exported from the MODULE, not from `./index.ts`: the panel surface's facet list draws the same
 * mark at the same edge, and two hand-drawn checks would drift.
 */
export function CheckGlyph(): ReactNode {
  return (
    <svg
      width={16}
      height={16}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={2.25}
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <path d="M5 12.5l5 5l9 -11" />
    </svg>
  )
}

/**
 * Names a control that has no VISIBLE Mantine `label`, and does it differently per surface — which
 * is the whole reason this is one helper instead of an `aria-label` sprinkled per call site.
 *
 * In the SHEET and the PANEL the visible `PanelRow` heading is right there, so the control points
 * at it (`aria-labelledby`) and the heading stops being decoration. In the PILL surface there is no
 * visible name to point at — the pill text is the VALUE (`EUR`, `30d`, `3 channels`) — so the
 * control carries the filter's own name instead. Either way the announced name is what is being
 * filtered, not what it currently holds.
 *
 * The id is generated by the CONTROL, not by `PanelRow`, because the control renders its own
 * `PanelRow`: an id published downward through context could never reach the sibling that needs it.
 *
 * @example
 * const { labelId, nameProps } = useControlName(label, inSheet || inPanel)
 * <Radio.Group {...nameProps} …/>
 * // and, in the sheet/panel branch: <PanelRow label={label} labelId={labelId}>…</PanelRow>
 */
export function useControlName(
  label: string,
  named: boolean,
): {
  labelId: string
  nameProps: { 'aria-labelledby': string } | { 'aria-label': string }
} {
  const labelId = useId()
  return {
    labelId,
    nameProps: named ? { 'aria-labelledby': labelId } : { 'aria-label': label },
  }
}
