/**
 * The mobile `Filters (n)` sheet and the two row primitives every control's sheet form composes
 * (`docs/CONTROLS-SPEC.md` §2.1/§3). A bottom `Drawer`: every child of the `FilterSet` renders its
 * full-width sheet form, edits APPLY IMMEDIATELY (there is no Apply button — the URL is the truth
 * and a filter write is already `history: 'replace'`), and one `Reset all` footer clears every
 * registered filter.
 *
 * 44px rows are the one sheet dimension C15 pins, so they come from
 * `--vx-space-sheet-row-height` — the density-tracking token, not a literal.
 *
 * INTERNAL, like `FilterPill`: `FilterSet` owns when the sheet opens, so a consumer mounting it by
 * hand would own a second, unregistered filter home (C1).
 */
import { Button, Drawer, Stack } from '@mantine/core'
import { useId } from 'react'
import type { ReactNode } from 'react'
import classes from './controls.module.css'

export type FilterSheetProps = {
  readonly opened: boolean
  readonly onClose: () => void
  readonly onResetAll: () => void
  readonly title?: string
  readonly children: ReactNode
}

export function FilterSheet({
  opened,
  onClose,
  onResetAll,
  title = 'Filters',
  children,
}: FilterSheetProps): ReactNode {
  return (
    <Drawer opened={opened} onClose={onClose} position="bottom" title={title} radius="sm">
      <div className={classes.sheetBody}>
        <Stack gap="sm">{children}</Stack>
        <div className={classes.sheetFooter}>
          <Button variant="default" size="ctl" onClick={onResetAll}>
            Reset all
          </Button>
        </div>
      </div>
    </Drawer>
  )
}

export type SheetFieldProps = {
  readonly label: string
  /** Stamped on the heading so a control can point `aria-labelledby` at it — see `useControlName`. */
  readonly labelId?: string
  readonly children: ReactNode
}

/** A labelled block inside the sheet — the sheet form's outer shell for every control. */
export function SheetField({ label, labelId, children }: SheetFieldProps): ReactNode {
  return (
    <div className={classes.sheetField}>
      <span className={classes.sheetLabel} {...(labelId !== undefined && { id: labelId })}>
        {label}
      </span>
      {children}
    </div>
  )
}

/**
 * Names a control that has no VISIBLE Mantine `label`, and does it differently per surface — which
 * is the whole reason this is one helper instead of an `aria-label` sprinkled per call site.
 *
 * In the SHEET the visible `SheetField` heading is right there, so the control points at it
 * (`aria-labelledby`) and the heading stops being decoration. In the PILL surface there is no
 * visible name to point at — the pill text is the VALUE (`EUR`, `30d`, `3 channels`) — so the
 * control carries the filter's own name instead. Either way the announced name is what is being
 * filtered, not what it currently holds.
 *
 * The id is generated by the CONTROL, not by `SheetField`, because the control renders its own
 * `SheetField`: an id published downward through context could never reach the sibling that needs it.
 *
 * @example
 * const { labelId, nameProps } = useControlName(label, inSheet)
 * <Radio.Group {...nameProps} …/>
 * // and, in the sheet branch: <SheetField label={label} labelId={labelId}>…</SheetField>
 */
export function useControlName(
  label: string,
  inSheet: boolean,
): {
  labelId: string
  nameProps: { 'aria-labelledby': string } | { 'aria-label': string }
} {
  const labelId = useId()
  return {
    labelId,
    nameProps: inSheet ? { 'aria-labelledby': labelId } : { 'aria-label': label },
  }
}

export type SheetRowProps = {
  readonly children: ReactNode
}

/** One 44px full-width row (`--vx-space-sheet-row-height`). */
export function SheetRow({ children }: SheetRowProps): ReactNode {
  return <div className={classes.sheetRow}>{children}</div>
}

/** The class every sheet-form list item shares, for controls that render their own row element. */
export const sheetRowClass = classes.sheetRow

/**
 * `classNames` for a Radio/Checkbox/Switch rendered as a sheet row — stretches its `body` and
 * `<label>` across the full 44px so the whole row is the touch target, not the middle 20px of it.
 */
export const sheetRowClassNames = {
  root: classes.sheetRow,
  body: classes.sheetRowBody,
  label: classes.sheetRowLabel,
} as const
