// GENERATED by scripts/gen-vx-names.ts — do not edit. `vx-names.test.ts` fails on drift.

/**
 * The families every emitted `--vx-*` name lives in (`basaltVxFamilies`) — basalt-owned:
 * `unknown-vx-token` judges every name inside one, and `groupTokens`/`seriesTokens` throw on a
 * consumer ref there.
 */
export const BASALT_VX_FAMILIES: readonly string[] = [
  'accent',
  'area',
  'axis',
  'bad',
  'crosshair',
  'divider',
  'dot',
  'faint',
  'fill',
  'good',
  'grid',
  'hit',
  'ink',
  'keyboard',
  'legend',
  'line',
  'muted',
  'neutral',
  'prose',
  'radius',
  'shadow',
  'space',
  'status',
  'surface',
  'text',
  'tooltip',
  'warn',
]
